---
sudo: required
language: bash
os:
  - linux
env:
  - ARCH=x86_64
addons:
  apt:
    update: true
    packages:
    ## File system ; https://www.olimex.com/wiki/AM335x#File_system
    # Install required tools: 
    - qemu-user-static
    - debootstrap
    - binfmt-support
script:
  - mkdir -p olimex
  - cp .travis.yml olimex

  # http://eewiki.net/display/linuxonarm/BeagleBoard#BeagleBoard-ARMCrossCompiler:GCC
  - wget -c https://releases.linaro.org/components/toolchain/binaries/6.4-2017.11/arm-linux-gnueabihf/gcc-linaro-6.4.1-2017.11-x86_64_arm-linux-gnueabihf.tar.xz
  - tar xf gcc-linaro-6.4.1-2017.11-x86_64_arm-linux-gnueabihf.tar.xz
  - export PATH=$(pwd)/gcc-linaro-6.4.1-2017.11-x86_64_arm-linux-gnueabihf/bin:$PATH
  # Test Cross Compiler:
  - arm-linux-gnueabihf-gcc --version

  - mkdir -p olimex/images
  # U-Boot ; https://www.olimex.com/wiki/AM335x#U-Boot
  # Building U-Boot
  # Get sources with:
  - git clone git://git.denx.de/u-boot.git && cd u-boot
  # The patch is built against specific commit, so reset repository:
  - git reset --hard b89dfcfd926b8224edd24608065eb9bb601c0d3b
  # Get and apply patch: 
  - wget https://raw.githubusercontent.com/OLIMEX/OLINUXINO/master/SOFTWARE/AM335x/patches/0001-Add-support-for-AM335x-Olimex-boards.patch
  - git apply 0001-Add-support-for-AM335x-Olimex-boards.patch
  # Build image, where <board_defconfig> is am335x_olimex_som_defconfig or am335x_olimex_som_nandboot_defconfig:
  - make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- distclean
  - make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- am335x_olimex_som_defconfig
  - make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-
  # This will produce two files: MLO, u-boot.img
  - cd -
  - cp u-boot/{u-boot.img,u-boot.bin,spl/u-boot-spl.bin} olimex/images

  - mkdir -p olimex/dts
  # Kernel ; https://www.olimex.com/wiki/AM335x#Kernel
  # Gettint the sources ; https://www.olimex.com/wiki/AM335x#Getting_the_sources
  # Clone into repository: 
  # Get 4.4.y remote branch:
  - git clone --depth 1 -b linux-4.4.y git://git.ti.com/ti-linux-kernel/ti-linux-kernel.git && cd ti-linux-kernel
  # Configure kernel ; https://www.olimex.com/wiki/AM335x#Configure_kernel
  # Load omap2plus default defconfig
  - make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- omap2plus_defconfig

deploy:
  provider: pages
  local-dir: olimex
  target-branch: ti
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: ti
    tags: true

env:
  global:
    secure: "pYbxCCez5zUTUk2eENF0vuDTWWwmlIsXmvbVs4ChWwK1mfz9O+ol0xIceRk80W8JasNeKYGqMvGFjKwj71LF40G1osvohUCTQAZzrjdoUClAspHWLRnROE0vCk3avHHgNf8Hb4KOYJdu4lFqKu50EufG/1xNaMQUDxWWShxH87yl9zDO28XLHntAdNlhXDES0dGY2CVZWyEuVDcoM39z8ZtUS+oy3+VdeRFCgU5KVkCb684MpvmY7zsDjfePegtucMq6QCKMbZvMZLUdkPOSra/JXKwq2rHJkC+Hf2OFn1mwRnKofL44PjPupbQuXq6yauMooR+ugo1OloUdkoBN7Xey+YaFNBY4Olfjsa+OXzdUt/49Ugya9cqRAzbp23VFBe2kju83oqRS4ZHac0aZkbzJw+Iiv4wnMBFuMTvn+A7ugoagPC3nRI8PhaUft1tb+LGwuCD6Arqc12anglUfU6SBd4f1X+PWEZM0KIK9MKDdzrZrh9V6YkZgrvagx8aBeN6cI9kpFxUlqQQdzV3+yOqs9wC3wHNqmNoGlOKbDQVZrhYr8JJ1gX4Mu8+lM1+iXnbU53fziRVMQlakB9oC2ylZEePrAVyGki9sjJVfjQKkT4zepX5eBrq6Y6PZiD9zZ7/4g9Xt4pm6uV8I+qZdRAoXRXG7H6esPkkSBpbTQv8="
