---
sudo: required
language: bash
os:
  - linux
env:
  - ARCH=x86_64
addons:
  apt:
    # 1. Setup of the toolchain
    # in the file below: 
    sources:
    - ubuntu-toolchain-r-test
    # Note that if you use debian may be you will need to add: 
    - sourceline: "deb http://www.emdebian.org/debian squeeze main"
    # Next update apt-get links by typing: 
    update: true
    # Next install the toolchain by typing the following: 
    packages:
    - gcc-4.7-arm-linux-gnueabihf
    - ncurses-dev
    - uboot-mkimage
    - build-essential
    - git
script:
  - export INPUT=$(git log -1 --oneline --pretty=%s)
  - |
    if [[ $INPUT =~ "--publish" ]];
      then
        export TRAVIS_TAG=1
    fi
  - mkdir -p olimex/{images,boot/dts,fs}
  - cp -f .travis.yml README.md olimex

  # 2. Building Uboot 
  # First let's make the directory where we would build the AM3352-SOM-olimex:
  - mkdir AM3352-SOM-olimex
  - cd AM3352-SOM-olimex


deploy:
  provider: pages
  local-dir: olimex
  target-branch: little-ti
  skip-cleanup: true
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  verbose: true
  on:
    branch: little-ti
    tags: true

env:
  global:
    secure: "pYbxCCez5zUTUk2eENF0vuDTWWwmlIsXmvbVs4ChWwK1mfz9O+ol0xIceRk80W8JasNeKYGqMvGFjKwj71LF40G1osvohUCTQAZzrjdoUClAspHWLRnROE0vCk3avHHgNf8Hb4KOYJdu4lFqKu50EufG/1xNaMQUDxWWShxH87yl9zDO28XLHntAdNlhXDES0dGY2CVZWyEuVDcoM39z8ZtUS+oy3+VdeRFCgU5KVkCb684MpvmY7zsDjfePegtucMq6QCKMbZvMZLUdkPOSra/JXKwq2rHJkC+Hf2OFn1mwRnKofL44PjPupbQuXq6yauMooR+ugo1OloUdkoBN7Xey+YaFNBY4Olfjsa+OXzdUt/49Ugya9cqRAzbp23VFBe2kju83oqRS4ZHac0aZkbzJw+Iiv4wnMBFuMTvn+A7ugoagPC3nRI8PhaUft1tb+LGwuCD6Arqc12anglUfU6SBd4f1X+PWEZM0KIK9MKDdzrZrh9V6YkZgrvagx8aBeN6cI9kpFxUlqQQdzV3+yOqs9wC3wHNqmNoGlOKbDQVZrhYr8JJ1gX4Mu8+lM1+iXnbU53fziRVMQlakB9oC2ylZEePrAVyGki9sjJVfjQKkT4zepX5eBrq6Y6PZiD9zZ7/4g9Xt4pm6uV8I+qZdRAoXRXG7H6esPkkSBpbTQv8="
