language: java
jdk: oraclejdk8
sudo: false
script:
  - mvn clean verify

  - ls Bonjour_Michel

  - git clone https://github.com/dejan-stankovic/meetup-ad-schematic.git
  - cd meetup-ad-schematic
  - mvn install compile package
  - java -jar target/final-altium-schematic-importer-1.0.jar -c $HOME/Bonjour_Michel/Sh_ADC-DAC_Main.SchDoc

cache:
  directories:
  - $HOME/.m2
